// <auto-generated />
namespace Oplog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstM));
        
        string IMigrationMetadata.Id
        {
            get { return "201512112105409_FirstM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
